--require "math"
--
--local function CartozoidEveryTenMinutes()
--    local playerX = math.floor(cartozoidPlayer:getX());
--    local playerY = math.floor(cartozoidPlayer:getY());
--
--    local deltaX = math.abs(playerX - cartozoidPlayerLastX);
--    local deltaY = math.abs(playerY - cartozoidPlayerLastY);
--    local totalDelta = math.sqrt(deltaX^2 + deltaY^2)
--
--    if totalDelta > POSITION_CHANGE_TOLERANCE then
--        local fileWriter = getFileWriter(cartozoidPlayerModData.CartozoidUUID..".txt", true, true);
--        fileWriter:writeln(playerX..";"..playerY..";;")
--        fileWriter:close()
--        cartozoidPlayerLastX = playerX;
--        cartozoidPlayerLastY = playerY;
--    end
--
--end
--
--Events.EveryTenMinutes.Add(CartozoidEveryTenMinutes);
